name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - { python: '3.8', experimental: false, coverage: false }
          - { python: '3.9', experimental: false, coverage: false }
          - { python: '3.10', experimental: false, coverage: true }
          - { python: '3.11.0-alpha.7', experimental: false, codecov: false }
    continue-on-error: ${{ matrix.experimental }}
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install python dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install codecov
      - name: Run tests
        run: make test
        env:
          PYTEST_ARGS: --cov-report=xml --cov=github_env
      - name: Check with flake8
        run: make flake8
      - name: Check with mypy
        run: make mypy
      - name: Check with isort
        run: make isort-check
      - name: Installation and usage
        run: |
          pip install .
          github_env.py --help
          github_env.py GITHUB_ENV_WORKS=yes
      - name: Check that the run succeeded
        run: test $GITHUB_ENV_WORKS == yes
      - name: Push coverage info
        run: codecov
        if: ${{ matrix.coverage }}
